#pragma once

enum class CodeType
{
	STORE_MEMORY_STATIC,			// mov [addr], val
	BEGIN_CONDITIONAL,
	END_CONDITIONAL,
	LOOP_START_END,
	LOAD_REGISTER_STATIC,			// mov reg, val
	LOAD_REGISTER_FROM_ADDRESS,		// mov reg, [addr] || mov reg, [reg]
	STORE_REGISTER_ADDRESS_STATIC,	// mov [reg], val
	ARITHMETIC_LEGACY,
	KEYPRESS_CONITIONAL,
	ARITHMETIC,
	STORE_REGISTER_TO_ADDRESS,		// mov [addr], reg
	RESERVED,
	EXTENDED_WIDTH_INSTRUCTION0,
	EXTENDED_WIDTH_INSTRUCTION1,
	EXTENDED_WIDTH_INSTRUCTION2,
	EXTENDED_WIDTH_INSTRUCTION3,
	BEGIN_REGISTER_CONDITIONAL = 0xC0,
	SAVE_RESTORE_REGISTER = 0xC1,
	SAVE_RESTORE_REGISTER_W_MASK = 0xC2,
	READ_WRITE_STATIC_REGISTER = 0xC3,
	DOUBLE_EXTENDED_WIDTH_INSTRUCTION = 0xF0,
	PAUSE_PROCESS = 0xFF0,
	RESUME_PROCESS = 0xFF1,
	DEBUG_LOG = 0xFFF,
	END_CODE,
	ERROR_TYPE,
	NEW_CODE_START,
	EMPTY_LINE
};
